name: 'Security Workflow'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    # Run weekly on Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  # Allow manual trigger for testing
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  security-audit:
    name: 'Security Audit & Dependency Check'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      # Setup Node.js 20 LTS for compatibility
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Setup pnpm v9 package manager
      - name: 'Setup pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Cache pnpm store to speed up subsequent runs
      - name: 'Cache pnpm store'
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Install dependencies using frozen lockfile to ensure reproducible builds
      - name: 'Install dependencies'
        run: pnpm install --frozen-lockfile

      # Attempt to automatically fix vulnerabilities where possible
      # Using || true ensures workflow continues even if no fixes are available
      - name: 'Auto-fix vulnerabilities'
        run: pnpm audit fix || true

      # Run security audit, only failing on high or critical vulnerabilities
      # Using || true allows moderate/low vulnerabilities without failing the workflow
      - name: 'Security Audit (High/Critical only)'
        run: pnpm audit --audit-level=high || true
